specs:
  /components:
    keys:
      - header
  /:
    keys:
      - app
      - components
  /components/header:
    keys:
      - name
      - props
  /components/header/name: {}
  /components/header/props:
    keys:
      - username
  /components/header/props/username:
    keys:
      - type
      - default
      - mapFromState
  /components/header/props/username/type: {}
  /components/header/props/username/default: {}
  /components/header/props/username/mapFromState: {}
generators:
  /react:
    keys:
      - id
  /:
    keys:
      - react
  /react/id: {}
