specs:
  /components:
    keys:
      - header
  /:
    keys:
      - app
      - components
  /components/header:
    keys:
      - name
  /components/header/name: {}
generators:
  /react:
    keys:
      - id
  /:
    keys:
      - react
  /react/id: {}
